### ISSUE TITLE
Inactive people appearing on team lists

### ISSUE THREAD

**Issue by osg-cat** [iris-hep/iris-hep.github.io#865]
It appears that people who have been marked as inactive are still appearing on the team lists, at least the overall team list and the focus area ones. What is the point of marking someone as inactive if they still show up? Please remove inactive people from “active” team lists.

**Comment by cranmer** [comment]
related, some people from steering board etc. are being displayed. Eg. Paolo on the AS page
https://iris-hep.org/as.html

**Comment by henryiii** [comment]
Do you have an overall team example? (@osg-cat). There's clear code attempting to remove inactive users from the full team list. (Focus areas probably was an oversight)

**Comment by osg-cat** [comment]
D’oh! My bad. I think what happened is that I searched for Edgar and my browser scrolled to the very bottom of the page. From there, I could not see the “Former Team Members” heading and so I thought it was all one big list. So yes, I agree that the full-team page (https://iris-hep.org/about/team) seems fine.

It would still be nice to get the focus area pages fixed, so that we can leave former team members’ focus area associations intact.

**Comment by davidlange6** [comment]
Yes. It's straightforward. I'll do it tomorrow if not already done by then

On May 10, 2021 9:07 PM, Tim Cartwright ***@***.***> wrote:

D’oh! My bad. I think what happened is that I searched for Edgar and my browser scrolled to the very bottom of the page. From there, I could not see the “Former Team Members” heading and so I thought it was all one big list. So yes, I agree that the full-team page (https://iris-hep.org/about/team) seems fine.

It would still be nice to get the focus area pages fixed, so that we can leave former team members’ focus area associations intact.
